
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbUIForms
{
    private readonly System.Collections.Generic.Dictionary<int, UIForms> _dataMap;
    private readonly System.Collections.Generic.List<UIForms> _dataList;
    
    public TbUIForms(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, UIForms>();
        _dataList = new System.Collections.Generic.List<UIForms>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            UIForms _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = UIForms.DeserializeUIForms(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, UIForms> DataMap => _dataMap;
    public System.Collections.Generic.List<UIForms> DataList => _dataList;

    public UIForms GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public UIForms Get(int key) => _dataMap[key];
    public UIForms this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

