
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class UIForms : Luban.BeanBase
{
    public UIForms(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
    }

    public static UIForms DeserializeUIForms(JSONNode _buf)
    {
        return new UIForms(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
   
    public const int __ID__ = 286395899;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "}";
    }
}

}

